nodeLinker: pnp

yarnPath: .yarn/releases/yarn-berry.cjs

#npmRegistryServer: https://registry.npm.taobao.org/

#globalFolder: C:\\Users\\qxqs1\\AppData\\Local\\Yarn\\Berry
#cacheFolder: 'D:\\Dev\\Web\\React\\craco-tests\\my-craco-app-ts\\.yarn\\cache'
